fullstackecommercewebapp/Models/Attributes.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace fullstackecommercewebapp.Models
{
    public partial class Attributes : BaseEntity
    {
        public Attributes()
        {
            CategoryAttribute = new HashSet<CategoryAttribute>();
            ProductAttributeValue = new HashSet<ProductAttributeValue>();
        }
       
        public int Id { get; set; }
        [Display(Name = "Attribute Name")]
        public string Name { get; set; }

        public virtual ICollection<CategoryAttribute>? CategoryAttribute { get; set; }
        public virtual ICollection<ProductAttributeValue>? ProductAttributeValue { get; set; }
    }
}

fullstackecommercewebapp/ViewModels/AttributeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace fullstackecommercewebapp.ViewModels
{
    public class AttributeViewModel
    {
        public AttributeViewModel()
        {
        }

        [Required(ErrorMessage = "Attribute Name must not be empty")]
        [Display(Name = "Attribute Name")]
        public string Name { get; set; }

    }
}

fullstackecommercewebapp/Controllers/AttributeController.cs
using AutoMapper;
using fullstackecommercewebapp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PagedList;

namespace fullstackecommercewebapp.Controllers
{
    [Authorize(Roles = "Administrator, Products Manager")]
    public class AttributeController : BaseController
    {
        public static string msg = "";
        public IActionResult Index(string sortOrder, string CurrentFilter, string SearchString, int? page)
        {
            ViewBag.msg = msg;
            msg = "";
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.CurrentSort = sortOrder;
            var attributes = _uow.attributeRepo.getAll();
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = CurrentFilter;
            }
            ViewBag.CurrentFilter = SearchString;
            if (!String.IsNullOrEmpty(SearchString))
            {
                attributes = attributes.Where(s => s.Name.ToLower().Contains(SearchString.ToLower()));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    attributes = attributes.OrderByDescending(s => s.Name);
                    break;
                default:
                    attributes = attributes.OrderBy(s => s.Name);
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(attributes.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public IActionResult Add()
        {
            AttributeViewModel avm = new AttributeViewModel();
            return View(avm);
        }


        [HttpPost]
        public IActionResult Add(AttributeViewModel avm)
        {
            if (ModelState.IsValid)
            {
                var config = new MapperConfiguration(cfg => cfg.CreateMap<AttributeViewModel, Models.Attributes>());
                var mapper = new Mapper(config);
                fullstackecommercewebapp.Models.Attributes a = mapper.Map<Models.Attributes>(avm);
                if (_uow.attributeRepo.checkUnique(a.Name) != 0)
                {
                    ModelState.AddModelError("Name", "Attribute Name must be unique");
                    return View(avm);
                }
                _uow.attributeRepo.Add(a);
                _uow.SaveChanges();
            }
            else
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                return View(avm);
            }
            msg = "added";
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Models.Attributes attribute = _uow.attributeRepo.getById(id);
            if (attribute == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.id = id;
            AttributeViewModel avm = new AttributeViewModel();
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Models.Attributes, AttributeViewModel>());
            var mapper = new Mapper(config);
            mapper.Map(attribute, avm);
            return View(avm);
        }


        [HttpPost]
        public IActionResult Edit(AttributeViewModel avm)
        {
            if (ModelState.IsValid)
            {
                Models.Attributes attribute = _uow.attributeRepo.getById(Convert.ToInt32(Request.Form["id"]));
                var config = new MapperConfiguration(cfg => cfg.CreateMap<AttributeViewModel, Models.Attributes>());
                var mapper = new Mapper(config);
                mapper.Map(avm, attribute);
                int check = _uow.attributeRepo.checkUnique(attribute.Name);
                System.Diagnostics.Debug.WriteLine(check);
                if (check != 0 && check != attribute.Id)
                {
                    ModelState.AddModelError("Name", "Attribute Name must be unique");
                    return View(avm);
                }
                _uow.attributeRepo.Edit(attribute);
                _uow.SaveChanges();
            }
            else
            {
                ViewBag.Id = Request.Form["id"];
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                return View(avm);
            }
            msg = "edited";
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var attribute = _uow.attributeRepo.getById(id);
            if (attribute == null)
            {
                return RedirectToAction("Index");
            }
            int pId = _uow.attributeRepo.checkDelete(id);
            if (pId == 0)
            {
                _uow.attributeRepo.Delete(id);
                _uow.SaveChanges();
                msg = "deleted";
                return RedirectToAction("Index");
            }
            msg = "NoDelete";
            return RedirectToAction("Index");

        }
    }
}

fullstackecommercewebapp/Views/Attribute/Add.cshtml
@model fullstackecommercewebapp.ViewModels.AttributeViewModel

@{
    ViewData["Title"] = "Add";

}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>User Orders</title>
    <link rel="stylesheet" href="~/css/CRUD.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

    <link rel="stylesheet" href="~/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/aos.css">

    <link rel="stylesheet" href="~/css/ionicons.min.css">

    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/icomoon.css">
    <link rel="stylesheet" href="~/css/style.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <style>
        .validation-summary-errors ul {
            list-style: none;
        }
    </style>
</head>



<body>

    <div class="hero-wrap hero-bread" style="background-color: #dbcc8f; height:20px">
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Attribute</span></p>
                    <h1 class="mb-0 bread">Add new Attribute</h1>
                    <div asp-validation-summary="All" class="text-danger"> </div>
                </div>
            </div>
        </div>
    </div>




    <section class="ftco-section contact-section bg-light">
        <div style="margin:0 auto; width:60vw" class="container">
            <form asp-action="Add" method="post" id="form" class="bg-white p-5">
                <div>
                    <div class="form-group">
                        @Html.DisplayNameFor(model => model.Name)
                        <input class="form-control" asp-for="Name" /> <span asp-validation-for="Name" class="text-danger"> </span>
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary py-3 px-5"> Submit </button>
                </div>
            </form>
        </div>
        <div class="col-md-1 order-md-last d-flex"> </div>

        <div>
        </div>
    </section>


    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/js/google-map.js"></script>
    <script src="~/js/main.js"></script>

</body>

fullstackecommercewebapp/Views/Attribute/Edit.cshtml
@model fullstackecommercewebapp.ViewModels.AttributeViewModel


@{
    ViewData["Title"] = "Edit";

}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Edit Attribute</title>
    <link rel="stylesheet" href="~/css/CRUD.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

    <link rel="stylesheet" href="~/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/aos.css">

    <link rel="stylesheet" href="~/css/ionicons.min.css">

    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/icomoon.css">
    <link rel="stylesheet" href="~/css/style.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <style>
        .validation-summary-errors ul {
            list-style: none;
        }
    </style>
</head>



<body>

    <div class="hero-wrap hero-bread" style="background-color: #dbcc8f; height:20px">
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Attribute</span></p>
                    <h1 class="mb-0 bread">Add new Attribute</h1>
                    <div asp-validation-summary="All" class="text-danger"> </div>
                </div>
            </div>
        </div>
    </div>




    <section class="ftco-section contact-section bg-light">
        <div style="margin:0 auto; width:60vw" class="container">
            <form asp-action="Edit" method="post" id="form" class="bg-white p-5">
                <input type="hidden" value=@ViewBag.id name="id" />
                <div>
                    <div class="form-group">
                        @Html.DisplayNameFor(model => model.Name)
                        <input class="form-control" value="@Model.Name" asp-for="Name" /> <span asp-validation-for="Name" class="text-danger"> </span>
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary py-3 px-5"> Submit </button>
                </div>
            </form>
        </div>
        <div class="col-md-1 order-md-last d-flex"> </div>
        <div>
        </div>

    </section>


    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/js/google-map.js"></script>
    <script src="~/js/main.js"></script>

</body>

fullstackecommercewebapp/Views/Attribute/Index.cshtml
@model PagedList.IPagedList<fullstackecommercewebapp.Models.Attributes>
@using PagedList.Mvc;


@{
    ViewData["Title"] = "Attributes";
}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Attributes</title>
    <link rel="stylesheet" href="~/css/CRUD.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

    <link rel="stylesheet" href="~/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/aos.css">

    <link rel="stylesheet" href="~/css/ionicons.min.css">

    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/icomoon.css">
    <link rel="stylesheet" href="~/css/style.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script>
        function checkDelete(id) {
            var link = '@Url.ActionLink("Delete", "Attribute", new { id = "-1" })';
            link = link.replace("-1", id);
            Swal.fire({
                title: 'Are you sure you want to delete this Attribute?',
                text: "",
                icon: 'warning',
                showCancelButton: true,
                timer: 3600000,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = link;
                }
            })
        }
    </script>
    @{
        if (ViewBag.msg == "added")
        {
            <script>

                Swal.fire({
                    icon: 'success',
                    title: 'This Attribute has been added successfully',
                    showConfirmButton: false,
                    timer: 1500
                })
            </script>
        }
        if (ViewBag.msg == "edited")
        {
            <script>
                Swal.fire({
                    icon: 'success',
                    title: 'This Attribute has been edited successfully',
                    showConfirmButton: false,
                    timer: 1500
                })
            </script>
        }
        if (ViewBag.msg == "NoDelete")
        {
            <script>
                Swal.fire({
                    icon: 'error',
                    title: 'You can not delete this Attribute',
                    showConfirmButton: true
                })
            </script>
        }
        if (ViewBag.msg == "deleted")
        {
            <script>
                Swal.fire({
                    icon: 'success',
                    title: 'This Attribute has been deleted successfully',
                    showConfirmButton: false,
                    timer: 1500
                })
            </script>
        }
    }
</head>

<body>
    <div class="hero-wrap hero-bread" style="background-image: url('images/bg_6.jpg'); height:20px">
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>attribute</span></p>
                    <h1 class="mb-0 bread">Attributes</h1>
                    <div asp-validation-summary="All" class="text-danger"> </div>
                </div>
            </div>
        </div>
    </div>

    <section class="ftco-section ftco-cart">
        <div class="container">
            <div class="row float-right">
                <a asp-action="Add" class="btn btn-primary"><i class="material-icons">&#xE863;</i> <span>Add New Attribute</span></a>
            </div>

            <div class="row" style="height:45px"></div>
            <div class="row table-filter">
                @using (Html.BeginForm("Index", "Attribute", FormMethod.Get))
                {
                    <div class="filter-group" style="width:50px;">
                        <button type="submit" style="background-color:transparent; border:hidden; width:50px;"><i style="width:50px;" class="fa fa-search"></i> </button>
                    </div>
                    <div class="filter-group">
                        <label> Attribute Name</label>
                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                    </div>
                    <span class="filter-icon"><i class="fa fa-filter"></i></span>
                }
            </div>
            <div class="row">
                <div class="col-md-12 ftco-animate">
                    <div class="cart-list">
                        <table class="table table-striped table-hover">
                            <thead class="thead-primary">
                                <tr class="text-center">
                                    <th class="align-middle">
                                        @Html.ActionLink("Name", "Index", new
                                        {
                                        sortOrder = ViewBag.NameSortParm,
                                        CurrentFilter = ViewBag.CurrentFilter
                                        },
                                        new { title = "Sort By Name", style = "color:white" })
                                    </th>
                                    <th class="align-middle">
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr class="text-center">
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td style="width:20%">
                                            <a asp-action="Edit" asp-route-id="@item.Id" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                                            <a onclick="checkDelete(@item.Id);" style="cursor:pointer" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="clearfix row">
                <div class="hint-text">Page <b>@Model.PageNumber</b> out of <b> @Model.PageCount</b> pages</div>

                <ul class="pagination">
                    <li class="page-item disabled"><a href="#"><i class="fa fa-angle-double-left"></i></a></li>
                    @for (int i = 1; i <= Model.PageCount; i++)
                    {
                        <li class="@(i == Model.PageNumber ? "page-item active" : "page-item")">
                            <a class="page-link" href="@Url.Action("Index", new { page = i,
                                            sortOrder = ViewBag.CurrentSort,
                                            CurrentFilter = ViewBag.CurrentFilter })">@i</a>
                        </li>
                    }
                    <li class="page-item"><a href="#" class="page-link"><i class="fa fa-angle-double-right"></i></a></li>
                </ul>
            </div>
        </div>
    </section>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/js/google-map.js"></script>
    <script src="~/js/main.js"></script>

</body>